// ─── Feature Verifier Specs ───────────────────────────────────────────────────
// One FeatureVerifierSpec per feature covering all 31 probed routes.
// These specs drive the probe execution engine in /api/verify/route.ts.

import type { FeatureVerifierSpec } from "./types";
import { DEFAULT_FEATURE_PASS_RULES } from "./types";

// ── AI Assistant ──────────────────────────────────────────────────────────────

export const aiAssistantFeature: FeatureVerifierSpec = {
  id: "ai_assistant",
  name: "AI Assistant",
  description: "Streaming assistant response generation and persistence",
  tags: ["core", "streaming", "llm"],
  requiredLevels: ["route", "dependency", "configuration", "connectivity", "permission", "functional", "integrity", "end_to_end"],
  dependencies: [
    { id: "openai_sdk", kind: "npm_package", name: "openai", required: true },
    { id: "anthropic_sdk", kind: "npm_package", name: "@anthropic-ai/sdk", required: false },
  ],
  configuration: [
    { id: "openai_api_key", kind: "env", name: "OPENAI_API_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "anthropic_api_key", kind: "env", name: "ANTHROPIC_API_KEY", required: false, redacted: true, validator: "non_empty" },
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "supabase_srk", kind: "secret", name: "SUPABASE_SERVICE_ROLE_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "table_conversations", kind: "db_schema", name: "assistant_conversations", required: true },
    { id: "table_messages", kind: "db_schema", name: "assistant_messages", required: true },
  ],
  permissions: [
    { id: "openai_generate", resource: "openai:model", action: "generate", required: true },
    { id: "db_conversation_write", resource: "table:assistant_conversations", action: "write", required: true },
  ],
  probes: [
    {
      id: "ai_assistant_route_exists",
      name: "AI Assistant route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/ai-assistant", body: { messages: [] } },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "ai_assistant_openai_installed",
      name: "OpenAI SDK installed",
      category: "package_installed",
      level: "dependency",
      severity: "critical",
      required: true,
      timeoutMs: 3000,
      runMode: "system",
    },
    {
      id: "ai_assistant_openai_key",
      name: "OpenAI API key configured",
      category: "env_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 1000,
      runMode: "system",
    },
    {
      id: "ai_assistant_conversations_table",
      name: "assistant_conversations table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "ai_assistant_messages_table",
      name: "assistant_messages table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "ai_assistant_openai_reachable",
      name: "OpenAI reachable",
      category: "service_reachable",
      level: "connectivity",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "ai_assistant_openai_credential",
      name: "OpenAI credential valid",
      category: "credential_valid",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "ai_assistant_stream_start",
      name: "Assistant stream starts",
      category: "stream_start",
      level: "functional",
      severity: "critical",
      required: true,
      timeoutMs: 15000,
      runMode: "service_role",
      input: {
        method: "POST",
        route: "/api/ai-assistant",
        body: { messages: [{ role: "user", content: "Reply with the single word: READY" }], context: {} },
      },
      expects: { expectedHttpStatus: 200, streamMustStart: true },
      integrity: [
        { id: "has_first_delta", type: "stream_has_first_delta" },
        { id: "has_finish_event", type: "stream_has_finish_event" },
      ],
    },
    {
      id: "ai_assistant_message_persisted",
      name: "Conversation persisted after stream",
      category: "side_effect_confirmed",
      level: "integrity",
      severity: "high",
      required: true,
      timeoutMs: 8000,
      runMode: "service_role",
      expects: { expectedSideEffect: { type: "message_persisted", resource: "table:assistant_conversations" } },
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, dependency: true, configuration: true, connectivity: true, permission: true, functional: true, integrity: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Conversations ─────────────────────────────────────────────────────────────

export const conversationsFeature: FeatureVerifierSpec = {
  id: "conversations",
  name: "Conversation Management",
  description: "Conversation list, load, search, delete",
  tags: ["core", "persistence"],
  requiredLevels: ["route", "guard", "configuration", "permission", "functional"],
  configuration: [
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "supabase_srk", kind: "secret", name: "SUPABASE_SERVICE_ROLE_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "table_conversations", kind: "db_schema", name: "assistant_conversations", required: true },
    { id: "table_messages", kind: "db_schema", name: "assistant_messages", required: true },
  ],
  permissions: [
    { id: "conversations_read", resource: "table:assistant_conversations", action: "read", required: true },
    { id: "conversations_delete", resource: "table:assistant_conversations", action: "delete", required: true },
  ],
  probes: [
    {
      id: "conversations_route_exists",
      name: "Conversations route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "GET", route: "/api/conversations" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
    {
      id: "conversations_auth_guard",
      name: "Conversations auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "GET", route: "/api/conversations" },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "conversations_table_exists",
      name: "assistant_conversations table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "conversations_permission_read",
      name: "Conversations readable via service role",
      category: "permission_read",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "conversations_search_route",
      name: "Conversation search route exists",
      category: "route_exists",
      level: "route",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "GET", route: "/api/conversations/search?q=test" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, permission: true, functional: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Brain Memory ──────────────────────────────────────────────────────────────

export const brainMemoryFeature: FeatureVerifierSpec = {
  id: "brain_memory",
  name: "Brain Memory",
  description: "Assistant memory read/write for context persistence",
  tags: ["core", "memory"],
  requiredLevels: ["route", "guard", "configuration", "permission"],
  configuration: [
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "table_memory", kind: "db_schema", name: "assistant_memory", required: true },
  ],
  permissions: [
    { id: "memory_read", resource: "table:assistant_memory", action: "read", required: true },
    { id: "memory_write", resource: "table:assistant_memory", action: "write", required: true },
  ],
  probes: [
    {
      id: "brain_route_exists",
      name: "Brain route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "GET", route: "/api/brain" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
    {
      id: "brain_auth_guard",
      name: "Brain auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "GET", route: "/api/brain" },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "brain_memory_table",
      name: "assistant_memory table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "brain_permission_read",
      name: "Memory readable via service role",
      category: "permission_read",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "brain_permission_write",
      name: "Memory writable via service role",
      category: "permission_write",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── File Intelligence ─────────────────────────────────────────────────────────

export const fileIntelligenceFeature: FeatureVerifierSpec = {
  id: "file_intelligence",
  name: "File Intelligence",
  description: "File upload, intake, search, and chunking",
  tags: ["files", "storage", "rag"],
  requiredLevels: ["route", "guard", "configuration", "permission", "functional", "integrity"],
  dependencies: [
    { id: "storage_adapter", kind: "node_module", name: "@supabase/storage-js", required: true },
    { id: "files_bucket", kind: "bucket", name: "files", required: true },
  ],
  configuration: [
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "supabase_srk", kind: "secret", name: "SUPABASE_SERVICE_ROLE_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "table_files", kind: "db_schema", name: "files", required: true },
    { id: "bucket_files", kind: "bucket", name: "files", required: true },
  ],
  permissions: [
    { id: "bucket_write", resource: "bucket:files", action: "write", required: true },
    { id: "bucket_read", resource: "bucket:files", action: "read", required: true },
  ],
  probes: [
    {
      id: "file_upload_route_exists",
      name: "File upload route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/files/upload" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "file_upload_auth_guard",
      name: "File upload auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/files/upload", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "files_table_exists",
      name: "files table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "files_bucket_exists",
      name: "files storage bucket exists",
      category: "bucket_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "files_permission_write",
      name: "Files bucket write permitted",
      category: "permission_write",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "service_role",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Voice System ──────────────────────────────────────────────────────────────

export const voiceSystemFeature: FeatureVerifierSpec = {
  id: "voice_system",
  name: "Voice System",
  description: "STT via Whisper, TTS via ElevenLabs, voice datasets",
  tags: ["voice", "tts", "stt"],
  requiredLevels: ["route", "guard", "configuration", "connectivity", "permission"],
  configuration: [
    { id: "elevenlabs_key", kind: "env", name: "ELEVENLABS_API_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "openai_key", kind: "env", name: "OPENAI_API_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "table_voice_datasets", kind: "db_schema", name: "voice_datasets", required: true },
  ],
  permissions: [
    { id: "elevenlabs_tts", resource: "elevenlabs:tts", action: "generate", required: true },
    { id: "openai_whisper", resource: "openai:whisper", action: "generate", required: true },
  ],
  probes: [
    {
      id: "voice_speak_route",
      name: "Voice TTS route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "GET", route: "/api/voice/speak" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
    {
      id: "voice_transcribe_auth_guard",
      name: "Voice STT auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/voice/transcribe" },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "elevenlabs_key_present",
      name: "ElevenLabs API key configured",
      category: "env_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 1000,
      runMode: "system",
    },
    {
      id: "voice_datasets_table",
      name: "voice_datasets table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "medium",
      required: false,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "elevenlabs_reachable",
      name: "ElevenLabs reachable",
      category: "service_reachable",
      level: "connectivity",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "elevenlabs_credential",
      name: "ElevenLabs credential valid",
      category: "credential_valid",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, connectivity: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Image Generation ──────────────────────────────────────────────────────────

export const imageGenerationFeature: FeatureVerifierSpec = {
  id: "image_generation",
  name: "Image Generation",
  description: "AI image generation via OpenAI + realism enforcement",
  tags: ["generation", "image", "openai"],
  requiredLevels: ["route", "guard", "configuration", "connectivity", "permission"],
  configuration: [
    { id: "openai_key", kind: "env", name: "OPENAI_API_KEY", required: true, redacted: true, validator: "non_empty" },
    { id: "table_generations", kind: "db_schema", name: "generations", required: true },
    { id: "bucket_generations", kind: "bucket", name: "generations", required: true },
  ],
  permissions: [
    { id: "openai_image_generate", resource: "openai:images", action: "generate", required: true },
    { id: "generations_write", resource: "table:generations", action: "write", required: true },
  ],
  probes: [
    {
      id: "generate_image_route",
      name: "Image generation route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/generate-image" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "generate_image_auth_guard",
      name: "Image generation auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/generate-image", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "generations_table_exists",
      name: "generations table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "generations_bucket_exists",
      name: "generations storage bucket exists",
      category: "bucket_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "openai_image_reachable",
      name: "OpenAI reachable for image generation",
      category: "service_reachable",
      level: "connectivity",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "openai_image_credential",
      name: "OpenAI credential valid for images",
      category: "credential_valid",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 8000,
      runMode: "system",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, connectivity: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Video Generation ──────────────────────────────────────────────────────────

export const videoGenerationFeature: FeatureVerifierSpec = {
  id: "video_generation",
  name: "Video Generation",
  description: "T2V and I2V via Kling/Runway",
  tags: ["generation", "video", "kling"],
  requiredLevels: ["route", "guard", "configuration", "connectivity"],
  configuration: [
    { id: "kling_key", kind: "env", name: "KLING_API_KEY", required: false, redacted: true, validator: "non_empty" },
    { id: "runway_key", kind: "env", name: "RUNWAY_API_KEY", required: false, redacted: true, validator: "non_empty" },
    { id: "table_pipeline_jobs", kind: "db_schema", name: "pipeline_jobs", required: true },
  ],
  permissions: [
    { id: "video_generate", resource: "kling:video", action: "generate", required: false },
  ],
  probes: [
    {
      id: "video_scratch_route",
      name: "Video scratch route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/video/scratch" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "video_scratch_auth_guard",
      name: "Video scratch auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/video/scratch", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "video_render_route",
      name: "Video render route exists",
      category: "route_exists",
      level: "route",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/video/render" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "pipeline_jobs_table_video",
      name: "pipeline_jobs table exists for video",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "kling_reachable",
      name: "Kling API reachable",
      category: "service_reachable",
      level: "connectivity",
      severity: "high",
      required: false,
      timeoutMs: 8000,
      runMode: "system",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Pipeline Workspace ────────────────────────────────────────────────────────

export const pipelineWorkspaceFeature: FeatureVerifierSpec = {
  id: "pipeline_workspace",
  name: "Pipeline Workspace",
  description: "Pipeline run, run-node, session, editor, video render",
  tags: ["pipeline", "generation", "orchestration"],
  requiredLevels: ["route", "guard", "configuration", "permission"],
  configuration: [
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "table_pipeline_jobs", kind: "db_schema", name: "pipeline_jobs", required: true },
    { id: "table_pipeline_sessions", kind: "db_schema", name: "pipeline_sessions", required: true },
    { id: "table_pipeline_steps", kind: "db_schema", name: "pipeline_steps", required: false },
  ],
  permissions: [
    { id: "pipeline_read", resource: "table:pipeline_jobs", action: "read", required: true },
    { id: "pipeline_write", resource: "table:pipeline_jobs", action: "write", required: true },
  ],
  probes: [
    {
      id: "pipeline_run_node_route",
      name: "Pipeline run-node route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/pipeline/run-node" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "pipeline_run_node_auth_guard",
      name: "Pipeline run-node auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/pipeline/run-node", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "pipeline_run_validation_guard",
      name: "Pipeline run validation guard",
      category: "validation_guard",
      level: "guard",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/pipeline/run", body: {} },
      expects: { expectedHttpStatus: 400 },
    },
    {
      id: "editor_validation_guard",
      name: "Editor validation guard",
      category: "validation_guard",
      level: "guard",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/editor", body: {} },
      expects: { expectedHttpStatus: 400 },
    },
    {
      id: "pipeline_jobs_table",
      name: "pipeline_jobs table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "pipeline_sessions_table",
      name: "pipeline_sessions table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "pipeline_permission_read",
      name: "Pipeline jobs readable via service role",
      category: "permission_read",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Operator Dashboard ────────────────────────────────────────────────────────

export const operatorDashboardFeature: FeatureVerifierSpec = {
  id: "operator_dashboard",
  name: "Operator Dashboard",
  description: "Health, ledger, route status, integrations, metrics",
  tags: ["operator", "monitoring", "health"],
  requiredLevels: ["route", "guard", "connectivity"],
  configuration: [
    { id: "table_ledger", kind: "db_schema", name: "ledger_logs", required: false },
  ],
  probes: [
    {
      id: "operator_health_route",
      name: "Operator health route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "GET", route: "/api/operator/health" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
    {
      id: "operator_health_auth_guard",
      name: "Operator health auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "GET", route: "/api/operator/health" },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "openai_connectivity",
      name: "OpenAI connectivity",
      category: "service_reachable",
      level: "connectivity",
      severity: "high",
      required: false,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "anthropic_connectivity",
      name: "Anthropic connectivity",
      category: "service_reachable",
      level: "connectivity",
      severity: "high",
      required: false,
      timeoutMs: 8000,
      runMode: "system",
    },
    {
      id: "elevenlabs_connectivity",
      name: "ElevenLabs connectivity",
      category: "service_reachable",
      level: "connectivity",
      severity: "medium",
      required: false,
      timeoutMs: 8000,
      runMode: "system",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Job Queue ─────────────────────────────────────────────────────────────────

export const jobQueueFeature: FeatureVerifierSpec = {
  id: "job_queue",
  name: "Job Queue",
  description: "Pipeline job listing and status",
  tags: ["jobs", "queue"],
  requiredLevels: ["route", "guard", "configuration", "permission"],
  configuration: [
    { id: "table_pipeline_jobs", kind: "db_schema", name: "pipeline_jobs", required: true },
  ],
  permissions: [
    { id: "jobs_read", resource: "table:pipeline_jobs", action: "read", required: true },
  ],
  probes: [
    {
      id: "jobs_route_exists",
      name: "Jobs route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "GET", route: "/api/jobs" },
      expects: { allowedHttpStatuses: [200, 401] },
    },
    {
      id: "jobs_auth_guard",
      name: "Jobs auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "GET", route: "/api/jobs" },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "jobs_table_exists",
      name: "pipeline_jobs table exists",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
    {
      id: "jobs_permission_read",
      name: "Jobs readable via service role",
      category: "permission_read",
      level: "permission",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true, permission: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Song Pipeline ─────────────────────────────────────────────────────────────

export const songPipelineFeature: FeatureVerifierSpec = {
  id: "song_pipeline",
  name: "Song Generation",
  description: "AI song generation pipeline",
  tags: ["audio", "generation"],
  requiredLevels: ["route", "guard", "configuration"],
  configuration: [
    { id: "suno_key", kind: "env", name: "SUNO_API_KEY", required: false, redacted: true, validator: "non_empty" },
    { id: "udio_key", kind: "env", name: "UDIO_API_KEY", required: false, redacted: true, validator: "non_empty" },
  ],
  probes: [
    {
      id: "song_route_exists",
      name: "Song generation route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/audio/generate-song" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "song_auth_guard",
      name: "Song generation auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/audio/generate-song", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── URL Ingestion ─────────────────────────────────────────────────────────────

export const urlIngestionFeature: FeatureVerifierSpec = {
  id: "url_ingestion",
  name: "URL Ingestion",
  description: "URL, YouTube, and content analysis intake",
  tags: ["intake", "rag", "ingestion"],
  requiredLevels: ["route", "guard", "configuration"],
  configuration: [
    { id: "supabase_url", kind: "env", name: "NEXT_PUBLIC_SUPABASE_URL", required: true, validator: "url" },
    { id: "table_files", kind: "db_schema", name: "files", required: true },
  ],
  probes: [
    {
      id: "intake_url_route",
      name: "URL intake route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/intake/url" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "intake_url_auth_guard",
      name: "URL intake auth guard",
      category: "auth_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "unauthenticated",
      input: { method: "POST", route: "/api/intake/url", body: {} },
      expects: { expectedHttpStatus: 401 },
    },
    {
      id: "intake_youtube_route",
      name: "YouTube intake route exists",
      category: "route_exists",
      level: "route",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/intake/youtube" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "intake_analyze_route",
      name: "Intake analyze route exists",
      category: "route_exists",
      level: "route",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/intake/analyze" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "intake_files_table",
      name: "files table exists for intake",
      category: "db_schema_present",
      level: "configuration",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "service_role",
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true, configuration: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── Editor ────────────────────────────────────────────────────────────────────

export const editorFeature: FeatureVerifierSpec = {
  id: "editor",
  name: "Editor",
  description: "GitHub file editor with AI write-back",
  tags: ["editor", "github", "code"],
  requiredLevels: ["route", "guard"],
  configuration: [
    { id: "github_token", kind: "env", name: "GITHUB_TOKEN", required: false, redacted: true, validator: "non_empty" },
  ],
  probes: [
    {
      id: "editor_route_exists",
      name: "Editor route exists",
      category: "route_exists",
      level: "route",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/editor" },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
    {
      id: "editor_validation_guard",
      name: "Editor validation guard (empty body → 400)",
      category: "validation_guard",
      level: "guard",
      severity: "critical",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/editor", body: {} },
      expects: { expectedHttpStatus: 400 },
    },
    {
      id: "copilot_chat_route",
      name: "Copilot-chat alias route exists",
      category: "route_exists",
      level: "route",
      severity: "high",
      required: true,
      timeoutMs: 5000,
      runMode: "system",
      input: { method: "POST", route: "/api/copilot-chat", body: { messages: [] } },
      expects: { allowedHttpStatuses: [200, 400, 401] },
    },
  ],
  passRules: { ...DEFAULT_FEATURE_PASS_RULES, finalPassRequires: { route: true, guard: true } },
  reporting: { showProbeTable: true, showEvidence: true, showLatency: true, showExpectedVsActual: true },
};

// ── All features registry ─────────────────────────────────────────────────────

export const ALL_FEATURES: FeatureVerifierSpec[] = [
  aiAssistantFeature,
  conversationsFeature,
  brainMemoryFeature,
  fileIntelligenceFeature,
  voiceSystemFeature,
  imageGenerationFeature,
  videoGenerationFeature,
  pipelineWorkspaceFeature,
  operatorDashboardFeature,
  jobQueueFeature,
  songPipelineFeature,
  urlIngestionFeature,
  editorFeature,
];

export const FEATURE_REGISTRY: Record<string, FeatureVerifierSpec> = Object.fromEntries(
  ALL_FEATURES.map((f) => [f.id, f])
);

export const FEATURE_SET_MAP: Record<string, string[]> = {
  all: ALL_FEATURES.map((f) => f.id),
  assistant: ["ai_assistant", "conversations", "brain_memory"],
  files: ["file_intelligence", "url_ingestion"],
  voice: ["voice_system"],
  pipeline: ["pipeline_workspace", "job_queue"],
  generation: ["image_generation", "video_generation", "song_pipeline"],
  operator: ["operator_dashboard"],
  editor: ["editor"],
};
